version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: dontpad_backend
    ports:
      - "127.0.0.1:1234:1234"
    volumes:
      - yjs_data:/usr/src/app/db
    restart: unless-stopped
    environment:
      - PORT=1234
    networks:
      - dontpad_net

  frontend:
    build:
      context: ./frontend
    container_name: dontpad_frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dontpad_net

volumes:
  yjs_data:

networks:
  dontpad_net:
